# Generated by tools/art/import_glb.py. Session-only pilot; procedural fallback remains.
extends RefCounted

const MODELS := {
	"crownblade": {"path": "res://assets/imported/legendary/crownblade.glb", "category": "weapon", "tris": 2940, "size": Vector3(0.3605, 1.3878, 0.1669), "nodes": []},
	"starforged_helm": {"path": "res://assets/imported/legendary/starforged_helm.glb", "category": "armour", "tris": 3920, "size": Vector3(0.3955, 0.5527, 0.4128), "nodes": []},
	"titanheart_plate": {"path": "res://assets/imported/legendary/titanheart_plate.glb", "category": "armour", "tris": 4900, "size": Vector3(0.7501, 0.6024, 0.5468), "nodes": []},
}

const ITEMS := {
	"Crownblade": {"model": "crownblade", "icon": "res://assets/imported/legendary/crownblade.png"},
	"Starforged Helm": {"model": "starforged_helm", "icon": "res://assets/imported/legendary/starforged_helm.png"},
	"Titanheart Plate": {"model": "titanheart_plate", "icon": "res://assets/imported/legendary/titanheart_plate.png"},
}
