extends SceneTree

# Runs the IRPG-R01 economy baseline and writes its results.
#   godot --headless --path . -s res://tools/economy/baseline.gd
# Reads tools/economy/inputs.json. Writes docs/economy/baseline_results.json and
# docs/economy/baseline_tables.md. Takes about 25 minutes; the same inputs give the same
# files. See docs/ECONOMY_BASELINE.md for what the numbers mean.

const ModelScript = preload("res://tools/economy/baseline_model.gd")

const INPUTS := "res://tools/economy/inputs.json"
const RESULTS := "res://docs/economy/baseline_results.json"
const TABLES := "res://docs/economy/baseline_tables.md"

func _init() -> void:
	call_deferred("_run")

func _run() -> void:
	var inputs: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(INPUTS))
	var model := ModelScript.new()
	var started := Time.get_ticks_msec()
	var results: Dictionary = model.run(inputs, root)
	print("Baseline ran in %d s. Ledger failures: %d" % [(Time.get_ticks_msec() - started) / 1000, model.ledger_failures.size()])
	for failure in model.ledger_failures.slice(0, 10):
		push_error(failure)

	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(RESULTS.get_base_dir()))
	_write(RESULTS, JSON.stringify(results, "\t") + "\n")
	_write(TABLES, _tables(results))
	quit(1 if not model.ledger_failures.is_empty() else 0)

func _write(path: String, text: String) -> void:
	var file := FileAccess.open(ProjectSettings.globalize_path(path), FileAccess.WRITE)
	file.store_string(text)
	file.close()

func _percent(share: float) -> String:
	return "%.1f%%" % (share * 100.0)

func _tables(results: Dictionary) -> String:
	var inputs: Dictionary = results["inputs"]
	var lines: Array[String] = [
		"# Economy baseline tables",
		"",
		"Generated by `tools/economy/baseline.gd` from `tools/economy/inputs.json`. Do not edit;",
		"rerun the tool. What these mean, and their limits: [ECONOMY_BASELINE.md](../ECONOMY_BASELINE.md).",
		"",
		"Seed %d. Collection sample: %d accounts per cell for %d days. Progression sample: %d accounts per cell, simulated in full for %d days, then projected." % [
			int(inputs["seed"]), int(inputs["collection_accounts"]), int(inputs["days"]), int(inputs["sim_accounts"]), int(inputs["sim_hours"]) / 24],
		""
	]

	lines += ["## Draws: how often a draw is new, and how often it is useful", "",
		"New = an item not owned before. Useful = it was equipped as an upgrade or became the travelling companion. No effect = a relic, which does nothing in the game yet.", "",
		"| Cell | Window | Draws per day | New | Useful | No effect | Useful draws per day |", "|---|---|---:|---:|---:|---:|---:|"]
	for cell in results["cells"]:
		var windows: Dictionary = results["cells"][cell]["collection"]["windows"]
		for window in windows:
			var w: Dictionary = windows[window]
			lines.append("| %s | %s | %.2f | %s | %s | %s | %.3f |" % [cell, str(window).replace("days_", "").replace("_", "–"),
				w["draws_per_account_per_day"], _percent(w["new_item_share"]), _percent(w["useful_share"]), _percent(w["no_effect_share"]), w["useful_per_account_per_day"]])

	lines += ["", "## Collection: unique items owned (mean, with the unlucky tenth in brackets)", "",
		"| Cell | Day | Gear of 25 | Companions of 10 | Relics of 10 | Gear banner complete | Has %s |" % str(inputs["target_item"]), "|---|---:|---:|---:|---:|---:|---:|"]
	for cell in results["cells"]:
		var checkpoints: Dictionary = results["cells"][cell]["collection"]["checkpoints"]
		for day in checkpoints:
			var p: Dictionary = checkpoints[day]
			lines.append("| %s | %s | %.1f (%d) | %.1f (%d) | %.1f (%d) | %s | %s |" % [cell, str(day).trim_prefix("day_"),
				p["gear"]["mean"], int(p["gear"]["p10"]), p["companions"]["mean"], int(p["companions"]["p10"]), p["relics"]["mean"], int(p["relics"]["p10"]),
				_percent(p["gear_banner_complete_share"]), _percent(p["target_item_share"])])

	lines += ["", "## Gear worn: attack and health from equipment (mean, unlucky tenth in brackets)", "",
		"| Cell | Day | Gear attack | Gear health |", "|---|---:|---:|---:|"]
	for cell in results["cells"]:
		var checkpoints: Dictionary = results["cells"][cell]["collection"]["checkpoints"]
		for day in checkpoints:
			var p: Dictionary = checkpoints[day]
			lines.append("| %s | %s | %.1f (%d) | %.1f (%d) |" % [cell, str(day).trim_prefix("day_"),
				p["gear_attack"]["mean"], int(p["gear_attack"]["p10"]), p["gear_hp"]["mean"], int(p["gear_hp"]["p10"])])

	lines += ["", "## Token ledger: mean per account over the whole run", "",
		"| Cell | Starting | Purchased | Income | From salvage | Spent on draws | Salvage returned per token spent |", "|---|---:|---:|---:|---:|---:|---:|"]
	for cell in results["cells"]:
		var l: Dictionary = results["cells"][cell]["collection"]["token_ledger"]
		lines.append("| %s | %.0f | %.0f | %.0f | %.1f | %.1f | %s |" % [cell, l["tokens_started"], l["tokens_purchased"], l["tokens_income"],
			l["tokens_salvaged"], l["tokens_spent"], _percent(l["salvage_returned_per_token_spent"])])

	lines += ["", "## Progression: the adventurer over time (simulated in full)", "",
		"| Cell | Time | Level | Attack | Health | Attack from gear | Quests done | Gold | Deaths | Talents |", "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|"]
	for cell in results["cells"]:
		var progression: Dictionary = results["cells"][cell]["progression"]
		for point in progression.get("points", {}):
			var p: Dictionary = progression["points"][point]
			var hour := int(str(point).trim_prefix("hour_"))
			lines.append("| %s | %s | %.0f | %.0f | %.0f | %.0f | %.0f | %.0f | %.0f | %.0f |" % [cell,
				"%d h" % hour if hour < 24 else "day %d" % (hour / 24),
				p["level"]["mean"], p["attack"]["mean"], p["health"]["mean"], p["gear_attack"]["mean"], p["quests"]["mean"], p["gold"]["mean"], p["deaths"]["mean"], p["talents"]["mean"]])

	lines += ["", "## Progression milestones (seconds of play, one value per simulated account)", "",
		"| Cell | First boss kill | Every talent learned |", "|---|---|---|"]
	for cell in results["cells"]:
		var progression: Dictionary = results["cells"][cell]["progression"]
		if not progression.is_empty():
			lines.append("| %s | %s | %s |" % [cell, str(progression["seconds_to_first_boss_kill"]), str(progression["seconds_to_all_talents"])])

	lines += ["", "## Projection beyond the simulated days", "",
		"Experience is extrapolated at the last simulated rate. The check column predicts the last simulated level from the stretch before it.", "",
		"| Cell | Experience per hour | Check: predicted vs actual level | Day | Level | Attack | Health |", "|---|---:|---|---:|---:|---:|---:|"]
	for cell in results["cells"]:
		var projection: Dictionary = results["cells"][cell]["progression"].get("projection", {})
		for day in projection.get("days", {}):
			var p: Dictionary = projection["days"][day]
			lines.append("| %s | %.0f | %.1f vs %.1f | %s | %.0f | %.0f | %.0f |" % [cell, projection["xp_per_hour"],
				projection["check_predicted_level_at_last_point"], projection["check_actual_level_at_last_point"], str(day).trim_prefix("day_"), p["level"], p["attack"], p["health"]])

	lines += ["", "## Power gap against the free cohort under the same income", "",
		"1.000 means equal. Rows marked projected are extrapolations.", "",
		"| Cell | Time | Attack ratio | Health ratio |", "|---|---|---:|---:|"]
	for cell in results["power_gaps"]:
		for point in results["power_gaps"][cell]:
			var g: Dictionary = results["power_gaps"][cell][point]
			var label := str(point)
			if label.begins_with("hour_"):
				var hour := int(label.trim_prefix("hour_"))
				label = "%d h" % hour if hour < 24 else "day %d" % (hour / 24)
			else:
				label = label.replace("day_", "day ").replace("_projected", " (projected)")
			lines.append("| %s | %s | %.3f | %.3f |" % [cell, label, g["attack_ratio"], g["health_ratio"]])

	lines.append("")
	return "\n".join(lines)
